import type { CaseData } from '../src/lib/forms/types.ts';

// Fictional test data. Long values are deliberate: they exercise wrapping and continuation pages.
export const sampleCase: CaseData = {
	'participant.name': 'Jordan A. Rivera',
	'participant.cin': 'AB12345C',
	'participant.dob': '1984-03-17',
	'participant.address': '418 Maple Avenue, Apt 2B, Albany, NY 12208',
	'participant.phone': '(518) 555-0142',
	'participant.county': 'Albany',
	'participant.countyFiscalResponsibility': 'Albany',
	'participant.currentLocation': 'Home / community',
	'participant.proposedResidence': '418 Maple Avenue, Apt 2B, Albany, NY 12208',
	'participant.emergencyContact.name': 'Maria Rivera (sister)',
	'participant.emergencyContact.phone': '(518) 555-0199',
	'participant.diagnosis':
		'Traumatic brain injury (S06.2X1S) following a motor vehicle accident; post-traumatic seizure disorder, controlled; mild expressive aphasia; depression secondary to injury.',
	'participant.injury.onsetDate': '2019-08-02',
	'participant.injury.ageAtOnset': '35',
	'participant.injury.cause': 'Motor vehicle accident',
	'participant.medicareNumber': '1EG4-TE5-MK73',
	'participant.otherInsurance': 'None',
	'participant.ssn': '000-00-0000',
	'participant.income': 'SSDI $1,420 / month',
	'participant.resources': 'Checking account under $2,000',
	'participant.spenddown': '0',
	'participant.repPayee': 'Maria Rivera',
	'guardian.name': '',
	'authRep.name': 'Maria Rivera',
	'scAgency.name': 'Capital Region Service Coordination, Inc.',
	'scAgency.address': '200 State Street, Suite 400, Albany, NY 12207',
	'scAgency.phone': '(518) 555-0110',
	'serviceCoordinator.name': 'Dana Okafor',
	'serviceCoordinator.phone': '(518) 555-0111',
	'serviceCoordinator.email': 'dokafor@example.org',
	'scSupervisor.name': 'Lee Chen',
	'provider.name': 'Hudson Valley Community Supports',
	'provider.medicaidId': '01234567',
	'provider.address': '55 River Road, Troy, NY 12180',
	'provider.phone': '(518) 555-0170',
	'provider.contact.name': 'Sam Patel',
	'provider.contact.title': 'Program Director',
	'rrdc.name': 'Capital District RRDC',
	'rrdc.region': 'Albany',
	'rrds.name': 'Pat Morgan',
	'rrds.title': 'Regional Resource Development Specialist',
	'intake.referralNumber': 'ALB-2026-0193',
	'medications.0.name': 'Levetiracetam',
	'medications.0.dose': '500 mg twice daily',
	'medications.0.purpose': 'Seizure prevention',
	'medications.0.prescriber': 'Dr. A. Singh',
	'medications.1.name': 'Sertraline',
	'medications.1.dose': '50 mg daily',
	'medications.1.purpose': 'Depression',
	'medications.1.prescriber': 'Dr. A. Singh',
	'supports.informal.0.name': 'Maria Rivera',
	'supports.informal.0.relationship': 'Sister',
	'supports.informal.0.phone': '(518) 555-0199',
	'supports.informal.0.support': 'Grocery shopping, medical appointments, weekly check-in',
	'supports.informal.1.name': 'St. Mark Community Center',
	'supports.informal.1.relationship': 'Community',
	'supports.informal.1.phone': '(518) 555-0130',
	'supports.informal.1.support': 'Tuesday social group',
	'services.0.type': 'Service Coordination',
	'services.0.provider': 'Capital Region Service Coordination, Inc.',
	'services.0.units': '4 hrs / month',
	'services.0.cost': '6200',
	'services.1.type': 'Independent Living Skills Training (ILST)',
	'services.1.provider': 'Hudson Valley Community Supports',
	'services.1.units': '6 hrs / week',
	'services.1.cost': '18720',
	'services.2.type': 'Community Integration Counseling (CIC)',
	'services.2.provider': 'Hudson Valley Community Supports',
	'services.2.units': '1 hr / week',
	'services.2.cost': '4680',
	'services.statePlan.0.type': 'Personal care aide',
	'services.statePlan.0.provider': 'Albany Home Care',
	'services.statePlan.0.frequency': '10 hrs / week',
	'incident.number': 'SRI-ALB-2026-044',
	'incident.occurredDate': '2026-10-05',
	'incident.occurredTime': '19:40',
	'incident.discoveredDate': '2026-10-05',
	'incident.discoveredTime': '20:15',
	'incident.location': 'Participant residence, kitchen',
	'incident.category': 'Hospitalization (unplanned)',
	'incident.description':
		'Participant had a breakthrough seizure while cooking dinner and fell, striking the left side of the head on the counter. Sister found the participant conscious but confused at 8:15 PM and called 911. EMS transported the participant to Albany Medical Center, where a CT scan showed no new bleeding. The participant was admitted overnight for observation and medication review. No staff were present at the time. The participant reported missing the evening dose of seizure medication two days in a row because the pharmacy refill was delayed.',
	'incident.actionsTaken':
		'Called 911; notified service coordinator at 9:05 PM; pharmacy contacted next morning to resolve refill delay; ILST worker scheduled a medication-routine session.',
	'incident.reporter.name': 'Sam Patel',
	'incident.reporter.title': 'Program Director',
	'incident.reporter.phone': '(518) 555-0170'
};
